### PR TITLE
fix(api): lint all dependencies in package-lock

### LINKED ISSUE #49: lockfile-lint does not lint the entire tree for package-lock.json
When running `"test:lockfile": "lockfile-lint -p package-lock.json -t npm -a npm -o https: -c -i",` it does not check past the first resolved URL for a dependency.

## Expected Behavior

`lockfile-lint` should check the entire tree.

## Current Behavior

If we take the below snippet from a `package-lock.json` and change the `semver` resolved URL to `http` or a URL other than `registry.npmjs.org`, `lockfile-lint` will not catch this.

```
"@babel/core": {
  "version": "7.7.5",
  "resolved": "https://registry.npmjs.org/@babel/core/-/core-7.7.5.tgz",
  "integrity": "sha512-M42+ScN4+1S9iB6f+TL7QBpoQETxbclx+KNoKJABghnKYE+fMzSGqst0BZJc8CpI625bwPwYgUyRvxZ+0mZzpw==",
  "dev": true,
  "requires": {
    "@babel/code-frame": "^7.5.5",
    "@babel/generator": "^7.7.4",
    "@babel/helpers": "^7.7.4",
    "@babel/parser": "^7.7.5",
    "@babel/template": "^7.7.4",
    "@babel/traverse": "^7.7.4",
    "@babel/types": "^7.7.4",
    "convert-source-map": "^1.7.0",
    "debug": "^4.1.0",
    "json5": "^2.1.0",
    "lodash": "^4.17.13",
    "resolve": "^1.3.2",
    "semver": "^5.4.1",
    "source-map": "^0.5.0"
  },
  "dependencies": {
    "semver": {
      "version": "5.7.1",
      "resolved": "https://registry.npmjs.org/semver/-/semver-5.7.1.tgz",
      "integrity": "sha512-sauaDf/PZdVgrLTNYHRtpXa1iRiKcaebiKQ1BJdpQlWH2lCvexQdX55snPFyK7QzpudqbCI0qXFfOasHdyNDGQ==",
      "dev": true
    },
    "source-map": {
      "version": "0.5.7",
      "resolved": "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz",
      "integrity": "sha1-igOdLRAh0i0eoUyA2OpGi6LvP8w=",
      "dev": true
    }
  }
},
```

## Possible Solution

At the moment, my current possible solution is to find and loop over all the `resolved` URLs.

## Steps to Reproduce (for bugs)

1. If you don't have a project with `lockfile-lint` in it already, create one and install `lockfile-lint`
2. Add a script that uses `lockfile-lint` (e.x. `"test:lockfile": "lockfile-lint -p package-lock.json -t npm -a npm -o https: -c -i"`)
3. Go into the `package-lock.json` and change the resolved URL to a dependency that is under `"dependencies"`
4. Run `lockfile-lint`

## Context

I cannot fully lint my entire `package-lock.json` file due to this.

## Your Environment

- Library Version used: `^3.0.8`
- Node.js version (e.g. Node.js 5.4): `v10.13.0`
- Operating System and version (desktop or mobile): macOS Mojave v10.14.5

### PR DESCRIPTION
**Pull request by JamesSingleton**
Will not override in the object if there is a matching dep and version
and will lint all the dependencies of dependencies.

Fixes #49

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Related Issue

https://github.com/lirantal/lockfile-lint/issues/49

## Motivation and Context

It solved the issue where if multiple dependencies had the same subdependencies (name and version) only one was added to the object. This was an issue if the first one was corrupt but the last one was fine, it would not be caught.

## How Has This Been Tested?

* Manually tested locally
* All unit tests are passing

## Checklist:

- [ ] I have updated the documentation (if required).
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I added a picture of a cute animal cause it's fun

### CODE REVIEW

**Comment by JamesSingleton** [comment]
One thing I want to mention is this now will not longer catch something like

```
 "lockfile-lint": {
      "version": "file:../lockfile-lint/packages/lockfile-lint/lockfile-lint-3.0.8.tgz",
      "integrity": "sha512-rS+Xbf31aGpj/vXAokFNjCobPEWT0IkeGpWY6ZwPdtlW80WAF13gZfkAIvxWvbl4yORhFvCXDOmSWzHCnBT78Q==",
      "dev": true,
      "requires": {
        "debug": "^4.1.1",
        "lockfile-lint-api": "file:../lockfile-lint/packages/lockfile-lint-api/lockfile-lint-api-5.0.7.tgz",
        "yargs": "^15.0.2"
      },
```

However, this I believe is a different issue all together and am willing to open an issue in regards to this.

**Comment by lirantal** [comment]
@JamesSingleton can you elaborate your last comment about why it would not catch that kind of structure and what exactly will be missed?

File: packages/lockfile-lint-api/src/ParseLockfile.js [hunk 1]
```diff
@@ -124,26 +125,26 @@ class ParseLockfile {
...
 
-  _flattenNpmDepsTree (npmDepsTree) {
-    let flattenedDepTree = {}
-    let flattenedNestedDepsTree = {}
+  _flattenNpmDepsTree (npmDepsTree, npmDepMap = {}) {
     for (const [depName, depMetadata] of Object.entries(npmDepsTree)) {
       const depMetadataShortend = {
         version: depMetadata.version,
-        resolved: depMetadata.resolved ? depMetadata.resolved : depMetadata.version,
+        resolved: depMetadata.resolved,
```
Comment (lirantal) [inline packages/lockfile-lint-api/src/ParseLockfile.js]: @JamesSingleton can you comment why was this changed?
IIRC this was supposed to solve cases where a resolved property may not be there but a version would, for cases like local file URLs or something like this.

**Comment by lirantal** [comment]
@JamesSingleton I see you've taken the approach of keeping the object structure but with a modification for it being a hash. Did you find this solution better than just changing it to an array structure?

File: packages/lockfile-lint-api/src/ParseLockfile.js (hunk 1 above)
Comment (lirantal) [reply packages/lockfile-lint-api/src/ParseLockfile.js]: So this is due to the `new URL(metadata.resolved)` failing if this is a version?
I'll track back the source of this and we'll find out.

Comment (lirantal) [reply packages/lockfile-lint-api/src/ParseLockfile.js]: From https://github.com/lirantal/lockfile-lint/issues/49#issuecomment-578963073

> The error points to this line
```let packageResolvedURL = {}
      try {
        packageResolvedURL = new URL(packageMetadata.resolved)
      } catch (error) {
        throw new PackageError(packageName, error)
      }
```
> Not sure how this is now just coming up now though. Looks like this will happen with any dependency that does not have a true URL for resolved since resolved is optional and doing new URL("1.1.1") is not a valid URL.

Sounds like you're saying this is a general bug unrelated to this change.
I tracked the source of using the version to a `package-lock.json` structure where the `version` field is used to specify the git URL, see here: https://github.com/lirantal/lockfile-lint/commit/a48311598b7f7e3e091d56e26d801894c00eb02b#diff-24ebf59c7b0eeb6040c5311942ef4a3eR16

**Comment by lirantal** [comment]
You've also referred to an issue with one of the tests in the last comment in the issue, here: https://github.com/lirantal/lockfile-lint/issues/49#issuecomment-579380305

Is this PR solving that or is that still something we need to fix?

**Comment by JamesSingleton** [comment]
> @JamesSingleton I see you've taken the approach of keeping the object structure but with a modification for it being a hash. Did you find this solution better than just changing it to an array structure?

@lirantal, I felt that it was a better solution in my opinion.

**Comment by lirantal** [comment]
@JamesSingleton in any specific way?
I mean, an object is nice because it's a dictionary structure that you can easily get the package if you know it's name/version but with the hash that's not possible anymore. I guess I could argue that it is much of a breaking change as just using arrays.

**Comment by JamesSingleton** [comment]
I keep the name and version along with the hash. The hash was just to make it unique and not have to redo all the validators.

File: packages/lockfile-lint-api/src/ParseLockfile.js (hunk 1 above)
Comment (lirantal) [reply packages/lockfile-lint-api/src/ParseLockfile.js]: @JamesSingleton nevermind here since we already have this discussion going on #54

**Comment by lirantal** [comment]
@JamesSingleton alright. I'm not entirely against doing as you proposed either but can assume that in the long run we will probably move to an array structure.

I'm ok to move forward with this

**Comment by JamesSingleton** [comment]
@lirantal can we move forward with merging this?

**Comment by Francois-Esquire** [comment]
Thank you @lirantal for taking time to work through and merge the PR! Question for you, when can we expect a release?

**Comment by lirantal** [comment]
New versions released 🎉
- lockfile-lint@3.0.10
- lockfile-lint-api@5.0.8

**Comment by lirantal** [comment]
thanks @JamesSingleton for your contribution on this 💜
